##       ____             __
##      / __ \_________ _/ /_____
##     / / / / ___/ __ `/ //_/ _ \
##    / /_/ / /  / /_/ / ,< /  __/  Clay Gomera (Drake)
##   /_____/_/   \__,_/_/|_|\___/   My custom starship prompt config
##

add_newline = false

[line_break]
disabled = true

[character]
error_symbol = "[âœ˜](bold red) "
success_symbol = "[â†³](bold green)"

[directory]
truncation_length = 5
home_symbol = "ðŸ "
format = "[$path](bold cyan) "

[hostname]
ssh_only = false
disabled = false
style = "bold italic #87A752"

[package]
disabled = true

[username]
show_always = true
style_user = "bold dimmed blue"
format =  "[$user]($style)[ in ](white)"
